Bebederos2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('admin/', admin.site.urls),
	path('', include('escuelas.urls', namespace="escuelas")), 
    path('', include('agua.urls', namespace="agua")),
    path('', include('expedientes.urls', namespace="expedientes")),
    path('', include('bebederos.urls', namespace="bebederos")),
    path('', include('mantenimientos.urls', namespace="mantenimientos")),
    path('', include('accounts.urls', namespace="accounts")),
    path('', include('incidencias.urls', namespace="incidencias")),    
]

#Media and static
from django.conf import settings
from django.conf.urls.static import static
 
#Media
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agua/urls.py
from django.urls import path
from .views import *

app_name = 'agua'

urlpatterns = [
	path('nuevo-analisis/escuela/<slug:slug>/', AnalisisCreateView.as_view(), name='analisis-create'),
	path('update-analisis/<slug:slug>/', AnalisisUpdateView.as_view(), name='analisis-update'),	
]

bebederos/urls.py
from django.urls import path
from .views import *

app_name = 'bebederos'

urlpatterns = [
#	path('nuevo-expediente/escuela/<slug:slug>/', ExpedienteCreateView.as_view(), name='expediente-create'),
	path('update-sistemabebedero/<slug:slug>/', SistemaBebederoUpdateView.as_view(), name='sistemabebedero-update'),	
]

escuelas/urls.py
from django.urls import path
from .views import *

app_name = 'escuelas'

urlpatterns = [
	path('escuela/<slug:slug>/', EscuelaDetailView.as_view(), name='escuela-detail'),
	path('entidad-convocatoria/<slug:slug>/', EntidadConvocatoriaDetailView.as_view(), name='entidad-convocatoria-detail'),
	path('entidad/<slug:slug>/', EntidadDetailView.as_view(), name='entidad-detail'),
	path('region/<slug:slug>/', RegionDetailView.as_view(), name='region-detail'),
	path('regiones/', RegionListView.as_view(), name='region-list'),
]

expedientes/urls.py
from django.urls import path
from .views import *

app_name = 'expedientes'

urlpatterns = [
	path('nuevo-expediente/escuela/<slug:slug>/', ExpedienteCreateView.as_view(), name='expediente-create'),
	path('update-expediente/<slug:slug>/', ExpedienteUpdateView.as_view(), name='expediente-update'),	
]

incidencias/urls.py
from django.urls import path
from .views import *

app_name = 'incidencias'

urlpatterns = [
	path('incidencia/update/<int:pk>/', IncidenciaUpdateView.as_view(), name='incidencia-update'),
	path('nueva-incidencia/escuela/<slug:slug>/', IncidenciaCreateView.as_view(), name='incidencia-create'),
	path('escuela/<slug:slug>/incidencias-y-notas/', IncidenciaListView.as_view(), name='incidencia-list'),
]

mantenimientos/urls.py
from django.urls import path
from .views import *

app_name = 'mantenimientos'

urlpatterns = [
	path('mantenimiento/update/<int:pk>/', MantenimientoUpdateView.as_view(), name='mantenimiento-update'),
	path('nuevo-mantenimiento/escuela/<slug:slug>/', MantenimientoCreateView.as_view(), name='mantenimiento-create'),
	path('escuela/<slug:slug>/mantenimientos/', MantenimientoListView.as_view(), name='mantenimiento-list'),
]

escuelas/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.utils import timezone
#from oficios.models import *

nivel_choices = (
	("Preescolar", "Preescolar"),
	("Primaria", "Primaria"),
	("Secundaria", "Secundaria"),
)

turno_choices = (
	("Matutino", "Matutino"),
	("Vespertino", "Vespertino"),
	("Tiempo Completo", "Tiempo Completo"),
)

class Region(models.Model):
	numero = models.IntegerField()
	nombre = models.CharField(max_length=20)
	slug = models.SlugField(max_length=50, blank=True, unique=True)

	def __str__(self):
		return '{} {}'.format(self.numero, self.nombre)

	def save(self):
		self.slug = '-'.join((slugify(self.numero), slugify(self.nombre)))
		super(Region, self).save()

class Convocatoria(models.Model):
	año = models.IntegerField()

	def __str__(self):
		return '{}'.format(self.año)

class Entidad(models.Model):
	region = models.ForeignKey(Region, verbose_name="Región", on_delete=models.CASCADE)
	partida = models.IntegerField()
	nombre = models.CharField(max_length=20)
	abreviatura	= models.CharField(max_length=4)
	slug = models.SlugField(max_length=50, blank=True, unique=True)

	def __str__(self):
		return '{}'.format(self.nombre)

	def save(self):
		self.slug= slugify(self.nombre)
		super(Entidad, self).save()

class EntidadConvocatoria(models.Model):
	entidad = models.ForeignKey(Entidad, on_delete=models.CASCADE)
	convocatoria = models.ForeignKey(Convocatoria, on_delete=models.CASCADE)
	escuelas_contractuadas = models.IntegerField()
	escuelas_registradas = models.IntegerField(default=0)
	escuelas_sustituidas = models.IntegerField(default=0)
	slug = models.SlugField(max_length=50, blank=True, unique=True)

	def __str__(self):
		return '{} {}'.format(self.entidad, self.convocatoria)

	def save(self):
		self.slug = '-'.join((slugify(self.entidad), slugify(self.convocatoria)))
		super(EntidadConvocatoria, self).save()

class Oficio(models.Model):
	nombre = models.TextField()
	archivo = models.FileField(upload_to='mantenimientos/%Y/%m/%d/')
	entidad_convocatoria = models.ForeignKey(EntidadConvocatoria, on_delete=models.CASCADE, null=True, blank=True, )
	fecha = models.DateTimeField(default=timezone.now)
	autor = models.CharField(max_length=50)

	def __str__(self):
		return '{} {}'.format(self.nombre, self.entidad_convocatoria)

class Escuela(models.Model):
	#Convocatoria
	entidad_convocatoria = models.ForeignKey(EntidadConvocatoria, on_delete=models.CASCADE)
	numero = models.IntegerField()
	#Administrativos
	cct = models.CharField(max_length=10)
	nombre = models.TextField()
	nivel_educativo = models.CharField(max_length=20, choices=nivel_choices)
	turno = models.CharField(max_length=20, default="Matutino", choices=turno_choices)
	plantilla_escolar = models.IntegerField()
	#Ubicacion
	municipio = models.CharField(max_length=50)
	domicilio = models.TextField()
	localidad = models.CharField(max_length=50)
	#Contacto
	director = models.CharField(max_length=50, blank=True, null=True)
	telefono = models.CharField(max_length=10, blank=True, null=True)
	esta_sustituida = models.BooleanField(default=False)
	es_sustitucion = models.BooleanField(default=False)
#	avance = models.IntegerField(blank=True, null=True)
#	evidencias = models.IntegerField(null=True, blank=True)
#	mantenimientos = models.IntegerField(null=True, blank=True)
	lista = models.ForeignKey(Oficio, on_delete=models.CASCADE)
	slug = models.SlugField(max_length=50, blank=True, unique=True)

	def save(self):
		self.slug = '-'.join((slugify(self.cct), slugify(self.nombre)))
		super(Escuela, self).save()

	def __str__(self):
		return '{} {}'.format(self.cct, self.nombre)

escuelas/views.py
from django.shortcuts import render
from .models import *
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from bebederos.models import *
from agua.models import *
from expedientes.models import *

class RegionListView(ListView):
	model = Region

class RegionDetailView(DetailView):
	model = Region

	def get_context_data(self, **kwargs):
		context = super(RegionDetailView, self).get_context_data(**kwargs)
		context['entidades'] = Entidad.objects.filter(region=self.object)
#		print(context['entidades'])
#		print(self.object)
		return context

class EntidadDetailView(DetailView):
	model = Entidad

	def get_context_data(self, **kwargs):
		context = super(EntidadDetailView, self).get_context_data(**kwargs)
		context['entidad_convocatorias'] = EntidadConvocatoria.objects.filter(entidad=self.object)
#		print(context['entidades'])
#		print(self.object)
		return context

class EntidadConvocatoriaDetailView(DetailView):
	model = EntidadConvocatoria

	def get_context_data(self, **kwargs):
		context = super(EntidadConvocatoriaDetailView, self).get_context_data(**kwargs)
		entidad_convocatoria = EntidadConvocatoria.objects.get(slug=self.object.slug)
		context['escuelas'] = Escuela.objects.filter(entidad_convocatoria=entidad_convocatoria)
		context['oficios'] = Oficio.objects.filter(entidad_convocatoria=entidad_convocatoria)	
#		print(context['entidades'])
#		print(self.object)
		return context	

class EscuelaDetailView(DetailView):
	model = Escuela

	def get_context_data(self, **kwargs):
		context = super(EscuelaDetailView, self).get_context_data(**kwargs)
		escuela = Escuela.objects.get(slug=self.kwargs['slug'])		
		context['sistemabebedero'] = SistemaBebedero.objects.get(escuela=escuela)
		context['numero_analisis'] = Analisis.objects.filter(escuela=escuela).count()
		context['analisis'] = Analisis.objects.filter(escuela=escuela)
		context['expediente'] = Expediente.objects.filter(escuela=escuela).count()
		context['expedientes'] = Expediente.objects.filter(escuela=escuela)		
#		print(context['entidades'])
#		print(self.object)
		return context		

escuelas/templates/escuelas/entidad_detail.html
{% extends 'base.html'%}

{%block content%}
	
	<a href="{%url 'escuelas:region-detail' object.region.slug%}">Regresar</a>

	<div class="table-responsive text-center">
		<table class="table">
			<thead>
				<th colspan="2">{{object.nombre}}</th>
			</thead>
			<thead>
				<th>Región</th>
				<th>Partida</th>
				
			</thead>
			<tbody>

				<tr>
					<td>{{object.region.numero}} {{object.region.nombre}}</td>
					<td>{{object.partida}}</td>
					
				</tr>
			</tbody>
		</table>
	</div>


	<h2></h2>

	<div class="table-responsive text-center">
		<table class="table">
			<thead>
				<th colspan="2">Convocatorias</th>
			</thead>
			<thead>
				<th>Convocatoria</th>
				<th>Escuelas contractuadas</th>	
			</thead>
			<tbody>

	{%for entidad_convocatoria in entidad_convocatorias%}

				<tr>
					<td><a href="{%url 'escuelas:entidad-convocatoria-detail' entidad_convocatoria.slug%}">{{entidad_convocatoria.convocatoria}}</a></td>
					<td>{{entidad_convocatoria.escuelas_contractuadas}}</td>
				</tr>
	
	{%empty%}
	
				<tr>
					<td colspan="3">Lista de regiones vacia</td>
				</tr>

	{%endfor%}

			</tbody>
		</table>
	</div>

{%endblock content%}

escuelas/templates/escuelas/entidadconvocatoria_detail.html
{% extends 'base.html'%}

{%block content%}

	<a href="{%url 'escuelas:entidad-detail' object.entidad.slug%}">Regresar</a>

	<div class="table-responsive text-center">
		<table class="table">
			<thead>
				<th colspan="2">{{object}}</th>
			</thead>
			<thead>
				<th>Región</th>
				<th>Partida</th>
			</thead>
			<tbody>
				<tr>
					<td>{{object.entidad.region}}</td>
					<td>{{object.entidad.partida}}</td>
				</tr>
			</tbody>
		</table>
	</div>


	<div class="table-responsive text-center">
		<table class="table">
			<thead>
				<th colspan="8">Documentación</th>
			</thead>
			<thead>
				<th>Nombre</th>
				<th>Fecha</th>
				<th>Subido por</th>
			</thead>
			<tbody>

	{%for oficio in oficios%}

				<tr>
					<td><a href="{{oficio.archivo.url}}">{{oficio.nombre}}</a></td>
					<td>{{oficio.fecha}}</td>
					<td>{{oficio.autor}}</td>
				</tr>
	
	{%empty%}
	
				<tr>
					<td colspan="8">Lista de escuelas vacia</td>
				</tr>

	{%endfor%}

			</tbody>
		</table>
	</div>



	<div class="table-responsive text-center">
		<table class="table">
			<thead>
				<th colspan="2">Reportes</th>
			</thead>
			<tbody>
				<tr>
					<td>
						<a href="">Reporte general (Proximamente)</a>
					</td>
				<tr>
				</tr>
					<td>
						<a href="">T7(Proximamente)</a>						
					</td>
				</tr>
			</tbody>
		</table>
	</div>

	<div class="table-responsive text-center">
		<table class="table">
			<thead>
				<th colspan="8">Escuelas</th>
			</thead>
			<thead>
				<th>Número</th>
				<th>CCT</th>
				<th>Nombre</th>
				<th>Municipio</th>
				<th>Localidad</th>
				<th>Plantilla</th>
				<th>Mueble</th>
				<th>Lista</th>			
			</thead>
			<tbody>

	{%for escuela in escuelas%}

				<tr>
					<td>{{escuela.numero}}</td>
					<td><a href="{%url 'escuelas:escuela-detail' escuela.slug%}">{{escuela.cct}}</a></td>
					<td>{{escuela.nombre}}</td>
					<td>{{escuela.municipio}}</td>
					<td>{{escuela.localidad}}</td>
					<td>{{escuela.plantilla_escolar}}</td>
					<td>{{escuela.escuela_sistemabebedero.mueble.modelo}}
					</td>
					<td><a href="{{escuela.lista.archivo.url}}">{{escuela.lista.nombre}} </a> {{escuela.lista.url}}
					</td>
				</tr>
	
	{%empty%}
	
				<tr>
					<td colspan="8">Lista de escuelas vacia</td>
				</tr>

	{%endfor%}

			</tbody>
		</table>
	</div>

{%endblock content%}

escuelas/templates/escuelas/escuela_detail.html
{% extends 'base.html'%}

{% load bootstrap %}

{%block content%}

	<a href="{%url 'escuelas:entidad-convocatoria-detail' object.entidad_convocatoria.slug%}">Regresar</a>
	
	<div class="table-responsive text-center">
		<table class="table">
			<thead>
				<th>Número</th>
				<th>CCT</th>
				<th>Nombre</th>
				<th>Convocatoria</th>				
			</thead>
			<tbody>
				<tr>
					<td>{{object.numero}}</td>
					<td>{{object.cct}}</td>
					<td>{{object.nombre}}</td>
					<td>{{object.entidad_convocatoria.convocatoria}}</td>
				</tr>
			</tbody>
		</table>

		<table class="table">
			<thead>
				<th>Turno</th>
				<th>Nivel educativo</th>
				<th>Plantilla</th>				
			</thead>
			<tbody>
				<tr>
					<td>{{object.turno}}</td>
					<td>{{object.nivel_educativo}}</td>
					<td>{{object.plantilla_escolar}}</td>			
				</tr>
			</tbody>
		</table>	

		<table class="table">
			<thead>
				<th>Domicilio</th>
				<th>Localidad</th>
				<th>Municipio</th>
				<th>Entidad</th>				
			</thead>
			<tbody>
				<tr>
					<td>{{object.domicilio}}</td>
					<td>{{object.localidad}}</td>
					<td>{{object.municipio}}</td>
					<td>{{object.entidad_convocatoria}}</td>					
				</tr>
			</tbody>
		</table>		


		<table class="table">
			<thead>
				<th>Modelo</th>
				<th>Sistema potabilizador</th>
			</thead>
			<tbody>
				<tr>
					<td>{{sistemabebedero.mueble.modelo}}</td>
					<td>{{sistemabebedero.sistema_potabilizador.tipo}}</td>
				</tr>
			</tbody>
		</table>

		<table class="table">
			<thead>
				<th>Director</th>
				<th>Teléfono</th>
			</thead>
			<tbody>
				<tr>
					<td>{{object.director}}</td>
					<td>{{object.telefono}}</td>
				</tr>
			</tbody>
		</table>		
	</div>

<div class="row">
  <div class="col-sm-4 h-100">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Notas</h5>
        <a href="{%url 'incidencias:incidencia-list' object.slug%}" class="btn btn-primary">Ver</a>
      </div>
    </div>
  </div>

  <div class="col-sm-4">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Primer análisis del agua</h5>

        {%if numero_analisis == 0%}
        <a href="{%url 'agua:analisis-create' object.slug%}" class="btn btn-primary">Crear</a>
        {%else%}
		<a href="{%url 'agua:analisis-update' analisis.0.slug%}" class="btn btn-primary">Actualizar</a>
		{%endif%}
      </div>
    </div>
  </div>

  <div class="col-sm-4">
    <div class="card h-100">
      <div class="card-body">
        <h5 class="card-title">Sistema bebedero</h5>
        <a href="{%url 'bebederos:sistemabebedero-update' sistemabebedero.slug%}" class="btn btn-primary">Configurar</a>
      </div>
    </div>
  </div>
</div>
<br>

<div class="row">
  <div class="col-sm-4">
    <div class="card h-100">
      <div class="card-body">
        <h5 class="card-title">Expediente técnico</h5>
        {%if expediente == 0%}
        <a href="{%url 'expedientes:expediente-create' object.slug%}" class="btn btn-primary">Crear</a>
		{%else%}
		<a href="{%url 'expedientes:expediente-update' expedientes.0.slug%}" class="btn btn-primary">Actualizar</a>
		{%endif%}
      </div>
    </div>
  </div>

  <div class="col-sm-4">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Segundo análisis del agua</h5>
		{%if numero_analisis == 1%}
        <a href="{%url 'agua:analisis-create' object.slug%}" class="btn btn-primary">Crear</a>
        {%elif numero_analisis == 2%}
		<a href="{%url 'agua:analisis-update' analisis.1.slug%}" class="btn btn-primary">Actualizar</a>
		{%else%}
		<a href="" class="btn btn-primary">Realizar el primer analisis</a>
		{%endif%}
      </div>
    </div>
  </div>

  <div class="col-sm-4">
    <div class="card h-100">
      <div class="card-body">
        <h5 class="card-title">Mantenimientos</h5>
        <a href="{%url 'mantenimientos:mantenimiento-list' object.slug%}" class="btn btn-primary">Ver y actualizar</a>
      </div>
    </div>
  </div>

</div>

{%endblock content%}

escuelas/templates/escuelas/region_detail.html
{% extends 'base.html'%}

{% load bootstrap %}

{%block content%}

	<a href="{%url 'escuelas:region-list'%}">Regresar</a>
	<div class="table-responsive text-center">
		<table class="table">
			<thead>
				<th colspan="2">Región</th>
			</thead>
			<thead>
				<th>Número</th>
				<th>Nombre</th>
			</thead>
			<tbody>

				<tr>
					<td>{{object.numero}}</td>
					<td>{{object.nombre}}</td>
				</tr>

			</tbody>
		</table>
	</div>

	<div class="table-responsive text-center">
		<table class="table">
			<thead>
				<th colspan="2">Entidades</th>
			</thead>
			<thead>
				<th>Partida</th>
				<th>Nombre</th>	
			</thead>
			<tbody>

	{%for entidad in entidades%}

				<tr>
					<td>{{entidad.partida}}</td>
					<td><a href="{%url 'escuelas:entidad-detail' entidad.slug%}">{{entidad.nombre}}</a></td>
				</tr>
	
	{%empty%}
	
				<tr>
					<td colspan="3">Lista de regiones vacia</td>
				</tr>

	{%endfor%}

			</tbody>
		</table>
	</div>

{%endblock content%}

escuelas/templates/escuelas/region_list.html
{% extends 'base.html'%}

{% load bootstrap %}

{%block content%}

	<div class="table-responsive text-center">
		<table class="table">
			<thead>
				<th colspan="2">Regiones</th>
			</thead>
			<thead>
				<th>Número</th>
				<th>Nombre</th>	
			</thead>
			<tbody>

	{%for region in object_list%}

				<tr>
					<td>{{region.numero}}</td>
					<td><a href="{%url 'escuelas:region-detail' region.slug%}">{{region.nombre}}</a></td>
				</tr>
	
	{%empty%}
	
				<tr>
					<td colspan="3">Lista de regiones vacia</td>
				</tr>

	{%endfor%}

			</tbody>
		</table>
	</div>

{%endblock content%}