Bebederos2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('admin/', admin.site.urls),
	path('', include('escuelas.urls', namespace="escuelas")), 
    path('', include('agua.urls', namespace="agua")),
    path('', include('expedientes.urls', namespace="expedientes")),
    path('', include('bebederos.urls', namespace="bebederos")),
    path('', include('mantenimientos.urls', namespace="mantenimientos")),
    path('', include('accounts.urls', namespace="accounts")),
    path('', include('incidencias.urls', namespace="incidencias")),    
]

#Media and static
from django.conf import settings
from django.conf.urls.static import static
 
#Media
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agua/urls.py
from django.urls import path
from .views import *

app_name = 'agua'

urlpatterns = [
	path('nuevo-analisis/escuela/<slug:slug>/', AnalisisCreateView.as_view(), name='analisis-create'),
	path('update-analisis/<slug:slug>/', AnalisisUpdateView.as_view(), name='analisis-update'),	
]

escuelas/urls.py
from django.urls import path
from .views import *

app_name = 'escuelas'

urlpatterns = [
	path('escuela/<slug:slug>/', EscuelaDetailView.as_view(), name='escuela-detail'),
	path('entidad-convocatoria/<slug:slug>/', EntidadConvocatoriaDetailView.as_view(), name='entidad-convocatoria-detail'),
	path('entidad/<slug:slug>/', EntidadDetailView.as_view(), name='entidad-detail'),
	path('region/<slug:slug>/', RegionDetailView.as_view(), name='region-detail'),
	path('regiones/', RegionListView.as_view(), name='region-list'),
]

mantenimientos/urls.py
from django.urls import path
from .views import *

app_name = 'mantenimientos'

urlpatterns = [
	path('mantenimiento/update/<int:pk>/', MantenimientoUpdateView.as_view(), name='mantenimiento-update'),
	path('nuevo-mantenimiento/escuela/<slug:slug>/', MantenimientoCreateView.as_view(), name='mantenimiento-create'),
	path('escuela/<slug:slug>/mantenimientos/', MantenimientoListView.as_view(), name='mantenimiento-list'),
]

mantenimientos/models.py
from django.db import models
from escuelas.models import Escuela
from django.utils import timezone

class Mantenimiento (models.Model):
	tipo_choices =  (
		('Preventivo' , 'Preventivo'),
		('Correctivo' , 'Correctivo'),
	)

	escuela = models.ForeignKey(Escuela, on_delete=models.CASCADE)
	creacion = models.DateTimeField(default=timezone.now, verbose_name="Fecha de creación")

	fecha = models.DateField(default=timezone.now, verbose_name="Fecha de mantenimiento")
	tipo = models.CharField(max_length=20, default="Preventivo", choices=tipo_choices)
	descripcion = models.TextField(null=True, blank=True, verbose_name="Descripción")
	volumen = models.IntegerField(verbose_name="Volumen indicado en medidor (Litros)")
			
	carnet = models.ImageField(verbose_name="Carnet actualizado", upload_to='mantenimientos/%Y/%m/%d/')
	foto_inicio = models.ImageField(verbose_name="Foto al iniciar el mantenimiento", upload_to='mantenimientos/%Y/%m/%d/')
	foto_fin = models.ImageField(verbose_name="Foto al finalizar el mantenimiento", upload_to='mantenimientos/%Y/%m/%d/')
	foto_medidor = models.ImageField(verbose_name="Foto del medidor", upload_to='mantenimientos/%Y/%m/%d/')

	def __str__(self):
		return '{} {}'.format(self.escuela, self.fecha)

mantenimientos/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from .models import * 
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse

class MantenimientoListView(ListView):
	model = Mantenimiento
#    template_name = 'products/products.html'
#    paginate_by = 5

	def get_context_data(self, **kwargs):
		context = super().get_context_data()
		escuela = Escuela.objects.get(slug=self.kwargs['slug'])
		context['escuela'] = escuela
		context['mantenimientos'] = Mantenimiento.objects.filter(escuela=escuela)
#		print(context['mantenimientos'])
#        print(self.kwargs['slug'])
		return context

class MantenimientoCreateView(CreateView):
	model = Mantenimiento
	fields = ['fecha', 'tipo', 'descripcion', 'volumen', 'carnet', 'foto_inicio', 'foto_fin', 'foto_medidor']

#	success_message = "¡Creacion exitosa!"

	def get_success_url(self):
		escuela = Escuela.objects.get(slug=self.kwargs['slug'])
		return reverse('mantenimientos:mantenimiento-list', args=(escuela.slug,))

	def form_valid(self, form):
		escuela = Escuela.objects.get(slug=self.kwargs['slug'])
		form.instance.escuela = escuela
		return super().form_valid(form)

	def get_context_data(self, **kwargs):
		context = super(MantenimientoCreateView, self).get_context_data(**kwargs)
		context['escuela'] = Escuela.objects.get(slug=self.kwargs['slug'])
		return context

class MantenimientoUpdateView(UpdateView):
	model = Mantenimiento
	fields = ['fecha', 'tipo', 'descripcion', 'volumen', 'carnet', 'foto_inicio', 'foto_fin', 'foto_medidor']

	success_message = "¡Actualizacion exitosa exitosa!"

	def get_success_url(self):
#		print(self.kwargs['pk'])
		mantenimiento = Mantenimiento.objects.get(pk=self.kwargs['pk'])
		escuela = mantenimiento.escuela
#		escuela = Escuela.objects.get(slug=self.kwargs['slug'])
		return reverse('mantenimientos:mantenimiento-list', args=(escuela.slug,))

	def get_context_data(self, **kwargs):
		context = super(MantenimientoUpdateView, self).get_context_data(**kwargs)
		mantenimiento = Mantenimiento.objects.get(pk=self.kwargs['pk'])
		context['escuela'] = mantenimiento.escuela
		return context

mantenimientos/templates/mantenimientos/mantenimiento_form.html
{% extends 'base.html'%}

{%load bootstrap%}

{%block content%}

	<a href="{%url 'mantenimientos:mantenimiento-list' escuela.slug%}">Regresar</a>

	<div class="table-responsive text-center">
		<table class="table">
			<thead>
				<th>{%if object%} Actualización{%else%} Creación{%endif%} de mantenimiento de la escuela {{escuela}}</th>
			</thead>
		</table>
	</div>
	
	<h2></h2>

	<form method="post" enctype="multipart/form-data">
		{%csrf_token%}
		{{form|bootstrap}}

		<input type="submit" value="Guardar cambios">
	</form>

{%endblock content%}

mantenimientos/templates/mantenimientos/mantenimiento_list.html
{% extends 'base.html'%}

{% load bootstrap %}

{%block content%}

	<h2></h2>

	<a href="{%url 'escuelas:escuela-detail' escuela.slug%}">Regresar</a>

	<div class="table-responsive text-center">
		<table class="table">
			<thead>
				<th>Mantenimientos de {{escuela}}</th>
			</thead>
		</table>
	</div>
	
	<a href="{%url 'mantenimientos:mantenimiento-create' escuela.slug%}">Nuevo mantenimiento</a>

	<div class="table-responsive text-center">
		<table class="table">
			<thead>
				<th>Fecha</th>
				<th>Tipo</th>
				<th>Descripción</th>
				<th>Volumen</th>
				<th>Foto del carnet</th>
				<th>Foto al inicio</th>		
				<th>Foto al final</th>
				<th>Foto del medidor</th>
				<th>Acciones</th>
			</thead>
			<tbody>

	{%for mantenimiento in mantenimientos%}

				<tr>
					<td>{{mantenimiento.fecha}}</td>
					<td>{{mantenimiento.tipo}}</td>
					<td>{{mantenimiento.descripcion}}</td>
					<td>{{mantenimiento.volumen}}</td>
					<td><a href="{{mantenimiento.carnet.url}}">Ver</a></td>	
					<td><a href="{{mantenimiento.foto_inicio.url}}">Ver</a></td>
					<td><a href="{{mantenimiento.foto_fin.url}}">Ver</a></td>
					<td><a href="{{mantenimiento.foto_medidor.url}}">Ver</a></td>

					<td><a href="{%url 'mantenimientos:mantenimiento-update' mantenimiento.pk%}">Modificar</a></td>										
				</tr>
	
	{%empty%}
	
				<tr>
					<td colspan="9">No hay mantenimientos</td>
				</tr>

	{%endfor%}

			</tbody>
		</table>
	</div>

{%endblock content%}