Bebederos2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('admin/', admin.site.urls),
	path('', include('escuelas.urls', namespace="escuelas")), 
    path('', include('agua.urls', namespace="agua")),
    path('', include('expedientes.urls', namespace="expedientes")),
    path('', include('bebederos.urls', namespace="bebederos")),
    path('', include('mantenimientos.urls', namespace="mantenimientos")),
    path('', include('accounts.urls', namespace="accounts")),
    path('', include('incidencias.urls', namespace="incidencias")),    
]

#Media and static
from django.conf import settings
from django.conf.urls.static import static
 
#Media
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
#from django.contrib.auth import login, logout
#from django.contrib.auth import authenticate, login
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
	path('login', auth_views.LoginView.as_view(template_name = 'accounts/login.html'), name='login'),
#	path('login', login.as_view(), name='login'),
	path('logout', auth_views.LogoutView.as_view(), name='logout'),	

	path('accounts/direccionador', views.Direccionador.as_view(), name="direccionador"),
    ]

agua/urls.py
from django.urls import path
from .views import *

app_name = 'agua'

urlpatterns = [
	path('nuevo-analisis/escuela/<slug:slug>/', AnalisisCreateView.as_view(), name='analisis-create'),
	path('update-analisis/<slug:slug>/', AnalisisUpdateView.as_view(), name='analisis-update'),	
]

escuelas/urls.py
from django.urls import path
from .views import *

app_name = 'escuelas'

urlpatterns = [
	path('escuela/<slug:slug>/', EscuelaDetailView.as_view(), name='escuela-detail'),
	path('entidad-convocatoria/<slug:slug>/', EntidadConvocatoriaDetailView.as_view(), name='entidad-convocatoria-detail'),
	path('entidad/<slug:slug>/', EntidadDetailView.as_view(), name='entidad-detail'),
	path('region/<slug:slug>/', RegionDetailView.as_view(), name='region-detail'),
	path('regiones/', RegionListView.as_view(), name='region-list'),
]

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title></title>

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Seguimiento de Bebederos</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
    </ul>
    {%if request.user.is_authenticated%}
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{%url 'escuelas:region-list'%}">Regiones</a>
        </li>      
        <li class="nav-item">
          <a class="nav-link" href="{%url 'accounts:logout'%}">Salir</a>
        </li>
      </ul>
    {%endif%}
  </div>
</nav>
<div class="container">
  <br>
	{%block content%}
	{%endblock content%}
  <br>
</div>
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
</body>
</html>