Bebederos2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('admin/', admin.site.urls),
	path('', include('escuelas.urls', namespace="escuelas")), 
    path('', include('agua.urls', namespace="agua")),
    path('', include('expedientes.urls', namespace="expedientes")),
    path('', include('bebederos.urls', namespace="bebederos")),
    path('', include('mantenimientos.urls', namespace="mantenimientos")),
    path('', include('accounts.urls', namespace="accounts")),
    path('', include('incidencias.urls', namespace="incidencias")),    
]

#Media and static
from django.conf import settings
from django.conf.urls.static import static
 
#Media
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agua/urls.py
from django.urls import path
from .views import *

app_name = 'agua'

urlpatterns = [
	path('nuevo-analisis/escuela/<slug:slug>/', AnalisisCreateView.as_view(), name='analisis-create'),
	path('update-analisis/<slug:slug>/', AnalisisUpdateView.as_view(), name='analisis-update'),	
]

escuelas/urls.py
from django.urls import path
from .views import *

app_name = 'escuelas'

urlpatterns = [
	path('escuela/<slug:slug>/', EscuelaDetailView.as_view(), name='escuela-detail'),
	path('entidad-convocatoria/<slug:slug>/', EntidadConvocatoriaDetailView.as_view(), name='entidad-convocatoria-detail'),
	path('entidad/<slug:slug>/', EntidadDetailView.as_view(), name='entidad-detail'),
	path('region/<slug:slug>/', RegionDetailView.as_view(), name='region-detail'),
	path('regiones/', RegionListView.as_view(), name='region-list'),
]

incidencias/urls.py
from django.urls import path
from .views import *

app_name = 'incidencias'

urlpatterns = [
	path('incidencia/update/<int:pk>/', IncidenciaUpdateView.as_view(), name='incidencia-update'),
	path('nueva-incidencia/escuela/<slug:slug>/', IncidenciaCreateView.as_view(), name='incidencia-create'),
	path('escuela/<slug:slug>/incidencias-y-notas/', IncidenciaListView.as_view(), name='incidencia-list'),
]

incidencias/models.py
from django.db import models
#from django.contrib.auth.models import User
from escuelas.models import *
from django.utils import timezone

class Incidencia(models.Model):
	status_choices = (
		("En espera", "En espera"),
		("Atendiendo", "Atendiendo"),
		("Solucionado", "Solucionado"),
		("No aplica", "No aplica"),
	)
	prioridad_choices = (
		("Ninguna", "Ninguna (Es una notificación)"),
		("Baja", "Baja"),
		("Media", "Media"),
		("Alta", "Alta"),
	)
	fase_choices = (
		("Primer análisis de agua", "Primer análisis de agua"),
		("Expediente técnico", "Expediente técnico"),
		("Construcción e instalación de Sistema bebedero", "Construcción e instalación de Sistema bebedero"),
		("Segundo análisis de agua", "Segundo análisis de agua"),
		("Mantenimientos", "Mantenimientos"),
	)

	escuela = models.ForeignKey(Escuela, on_delete=models.CASCADE)
	autor = models.CharField(max_length=50)
	descripcion = models.TextField(verbose_name="Descripción")
	status = models.CharField(max_length=30, default="En espera", choices=status_choices)
	prioridad = models.CharField(max_length=10, choices=prioridad_choices)
	solucion = models.TextField(verbose_name="Solución", null=True, blank=True)
	fecha_solucion = models.DateTimeField(verbose_name="Fecha de solucion", null=True, blank=True)
	creacion = models.DateTimeField(default=timezone.now, verbose_name="Fecha de creación")
	evidencia_incidencia = models.ImageField(upload_to="incidencias/%Y/%m/%d/", null=True, blank=True, verbose_name="Evidencia de incidencia")
	evidencia_solucion = models.ImageField(upload_to="incidencias/%Y/%m/%d/", null=True, blank=True, verbose_name="Evidencia de solución")

	def __str__(self):
		return '{}'.format(self.escuela)

	class Meta:
		ordering = ['creacion']

	def save(self):
		if self.status == "Solucionado":
			print("hola")
#			print(timezone.now())
			self.fecha_solucion = timezone.now()
			print(self.fecha_solucion)
		super(Incidencia, self).save()

incidencias/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from .models import * 
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse

class IncidenciaListView(ListView):
	model = Incidencia
#    template_name = 'products/products.html'
#    paginate_by = 5

	def get_context_data(self, **kwargs):
		context = super().get_context_data()
		escuela = Escuela.objects.get(slug=self.kwargs['slug'])
		context['escuela'] = escuela
		context['incidencias'] = Incidencia.objects.filter(escuela=escuela)
#		print(context['mantenimientos'])
#        print(self.kwargs['slug'])
		return context

class IncidenciaCreateView(CreateView):
	model = Incidencia
	fields = ['descripcion', 'status', 'prioridad', 'evidencia_incidencia']

#	success_message = "¡Creacion exitosa!"

	def get_success_url(self):
		escuela = Escuela.objects.get(slug=self.kwargs['slug'])
		return reverse('incidencias:incidencia-list', args=(escuela.slug,))

	def form_valid(self, form):
		escuela = Escuela.objects.get(slug=self.kwargs['slug'])
		form.instance.escuela = escuela
		form.instance.autor = self.request.user.first_name + " " + self.request.user.last_name
		return super().form_valid(form)

	def get_context_data(self, **kwargs):
		context = super(IncidenciaCreateView, self).get_context_data(**kwargs)
		context['escuela'] = Escuela.objects.get(slug=self.kwargs['slug'])
		return context

class IncidenciaUpdateView(UpdateView):
	model = Incidencia
	fields = ['descripcion', 'status', 'prioridad', 'evidencia_incidencia', 'solucion', 'evidencia_solucion']

	def get_success_url(self):
		incidencia = Incidencia.objects.get(pk=self.kwargs['pk'])
		escuela = incidencia.escuela
		return reverse('incidencias:incidencia-list', args=(escuela.slug,))

	def get_context_data(self, **kwargs):
		context = super(IncidenciaUpdateView, self).get_context_data(**kwargs)
		incidencia = Incidencia.objects.get(pk=self.kwargs['pk'])
		context['escuela'] = incidencia.escuela
		return context		

incidencias/templates/incidencias/incidencia_form.html
{% extends 'base.html'%}

{%load bootstrap%}

{%block content%}

	<a href="{%url 'incidencias:incidencia-list' escuela.slug%}">Regresar</a>

	<div class="table-responsive text-center">
		<table class="table">
			<thead>
				<th>{%if object%} Actualización{%else%} Creación{%endif%} de nota o incidencia de la escuela {{escuela}}</th>
			</thead>
		</table>
	</div>

	<form method="post" enctype="multipart/form-data">
		{%csrf_token%}
		{{form|bootstrap}}

		<input type="submit" value="Guardar cambios">
	</form>

{%endblock content%}

incidencias/templates/incidencias/incidencia_list.html
{% extends 'base.html'%}

{% load bootstrap %}

{%block content%}

	<a href="{%url 'escuelas:escuela-detail' escuela.slug%}">Regresar</a>

	<div class="table-responsive text-center">
		<table class="table">
			<thead>
				<th>Notas e incidencias de {{escuela}}</th>
			</thead>
		</table>

	</div>

	<a href="{%url 'incidencias:incidencia-create' escuela.slug%}">Nueva incidencia</a>

	<div class="table-responsive text-center">
		<table class="table">
			<thead>
				<th>Folio</th>
				<th>Autor</th>
				<th>Creación</th>
				<th>Descripción</th>
				<th>Prioridad</th>
				<th>Status</th>
				<th>Evidencia</th>
				<th>Solución</th>
				<th>Evidencia de solución</th>
				<th>Fecha de solución</th>
			</thead>
			<tbody>

	{%for incidencia in incidencias%}

				<tr>
					<td><a href="{%url 'incidencias:incidencia-update' incidencia.pk%}">{{incidencia.pk}}</a></td>
					<td>{{incidencia.autor}}</td>
					<td>
					{{incidencia.creacion}}</td>
					<td>{{incidencia.descripcion}}</td>
					<td>{{incidencia.prioridad}}</td>
					<td>{{incidencia.status}}</td>
					<td>{%if incidencia.evidencia_incidencia%}<a href="{incidencia.evidencia_incidencia.url}}">Ver</a>{%endif%}</td>
					<td>{%if incidencia.solucion%}{{incidencia.solucion}}{%endif%}</td>
					<td>{%if incidencia.evidencia_solucion%}<a href="{{incidencia.evidencia_solucion.url}}">Ver</a>{%endif%}</td>
					<td>{%if incidencia.fecha_solucion%}{{incidencia.fecha_solucion}}{%endif%}</td>
				</tr>
	
	{%empty%}
	
				<tr>
					<td colspan="9">No hay incidencias</td>
				</tr>

	{%endfor%}

			</tbody>
		</table>
	</div>

{%endblock content%}